#!/usr/bin/env bash
#configure an ubuntu server as follow:
# localhost to 127.0.0.2
# facebook to 8.8.8.8

cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
